name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'website/**'
      - '.github/workflows/**'
  
  # Allow manual deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials from GitHub Secrets
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        
    - name: Verify AWS connection
      run: |
        aws sts get-caller-identity
        echo "✅ AWS authentication successful"
        
    - name: Deploy to S3
      run: |
        echo "📤 Deploying website to S3..."
        aws s3 sync website/ s3://linknote.com/ --delete
        aws s3 sync website/ s3://www.linknote.com/ --delete
        echo "✅ S3 deployment complete"
        
    - name: Invalidate CloudFront cache
      run: |
        echo "♻️ Invalidating CloudFront cache..."
        aws cloudfront create-invalidation --distribution-id E2YEJACEYDBDX3 --paths "/*"
        echo "✅ CloudFront cache invalidated"
        
    - name: Deployment summary
      run: |
        echo "🌐 Deployment successful!"
        echo "Live site: https://linknote.com"
        echo "CDN: CloudFront distribution E2YEJACEYDBDX3"
        echo "Bucket: s3://linknote.com"